name: habitutor

services:
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.prod
    ports:
      - 3000:3000
    env_file: ./apps/web/.env.prod
    depends_on:
      server:
        condition: service_healthy

  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile.prod
    ports:
      - 3001:3001
    env_file: ./apps/server/.env.prod
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:3001/api-reference/healthcheck || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  db:
    image: postgres:18.0-alpine
    platform: linux/amd64
    container_name: habitutor-postgres
    environment:
      POSTGRES_DB: habitutor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db:
