name: habitutor-test

services:
  postgres-test:
    image: postgres:18-alpine
    container_name: habitutor-postgres-test
    environment:
      POSTGRES_DB: habitutor_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "6970:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
