name: habitutor

services:
  postgres:
    image: postgres:18-alpine
    container_name: habitutor-postgres
    environment:
      POSTGRES_DB: habitutor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - habitutor_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  habitutor_postgres_data:
